In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("insurance data.csv")

data.head(5)

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [4]:
data.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [5]:
x = data[['age', 'sex', 'bmi', 'children', 'smoker', 'region']]
y = data['charges']

In [7]:
x = pd.get_dummies(x, drop_first=True)

In [8]:
x.head(5)

,age,bmi,children,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,False,True,False,False,True
1,18,33.770,1,True,False,False,True,False
2,28,33.000,3,True,False,False,True,False
3,33,22.705,0,True,False,True,False,False
4,32,28.880,0,True,False,True,False,False

In [9]:
y.head(5)

0    16884.92400
1     1725.55230
2     4449.46200
3    21984.47061
4     3866.85520
Name: charges, dtype: float64

In [10]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.20, random_state=32)

In [11]:
print(x.head())
print(y.head())

   age     bmi  children  sex_male  smoker_yes  region_northwest  \
0   19  27.900         0     False        True             False
1   18  33.770         1      True       False             False
2   28  33.000         3      True       False             False
3   33  22.705         0      True       False              True
4   32  28.880         0      True       False              True

   region_southeast  region_southwest
0             False              True
1              True             False
2              True             False
3             False             False
4             False             False
0    16884.92400
1     1725.55230
2     4449.46200
3    21984.47061
4     3866.85520
Name: charges, dtype: float64

In [12]:
x_train.shape

(1070, 8)

In [13]:
x_test.shape

(268, 8)

In [14]:
y_train.shape, y_test.shape

((1070,), (268,))

In [15]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

In [16]:
lr.fit(x_train, y_train)

LinearRegression()

In [17]:
lr.coef_

array([  255.58814519,   343.64739945,   491.32488245,   -29.88157626,
       23694.06541215,  -583.0851085 , -1193.38367335, -1278.83614766])

In [18]:
lr.intercept_

np.float64(-11833.6495673138)

In [20]:
y_pred_train = lr.predict(x_train)

In [21]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

In [23]:
import math
math.sqrt(mean_squared_error(y_train, y_pred_train))

6186.3371733823205

In [24]:
r2_score(y_train, y_pred_train)

0.7436951911655163

In [25]:
mean_absolute_error(y_train, y_pred_train)

4297.262816905063

In [26]:
y_pred_test = lr.predict(x_test)

In [27]:
import math
math.sqrt(mean_squared_error(y_test, y_pred_test))

5436.188923107273

In [29]:
r2_score(y_test, y_pred_test)

0.781705116269015

In [30]:
mean_absolute_error(y_test, y_pred_test)

3828.807510594179

In [31]:
def lr_pred(age, sex, bmi, children, smoker, region):
    input_data = pd.DataFrame({
        'age': [age],
        'bmi': [bmi],
        'children': [children],
        'sex_male': [sex == 'male'],
        'smoker_yes': [smoker == 'yes'],
        'region_northwest': [region == 'northwest'],
        'region_southeast': [region == 'southeast'],
        'region_southwest': [region == 'southwest']
    })

    return lr.predict(input_data)

In [32]:
lr_pred(30, 'male', 25.5, 1, 'no', 'southeast')

array([3865.06310718])

In [34]:
age = int(input("Enter your age: "))
sex = input("Enter your sex (male/female): ").lower()
bmi = float(input("Enter your BMI: "))
children = int(input("Enter number of children: "))
smoker = input("Are you a smoker? (yes/no): ").lower()
region = input("Enter your region (southwest/southeast/northwest/northeast): ").lower()

prediction = lr_pred(age, sex, bmi, children, smoker, region)

print("\n========== Insurance Prediction ==========")
print(f"Age              : {age}")
print(f"Sex              : {sex}")
print(f"BMI              : {bmi}")
print(f"Children         : {children}")
print(f"Smoker           : {smoker}")
print(f"Region           : {region}")
print("------------------------------------------")
print(f"Predicted Charges : ${prediction}")
print("==========================================")

Enter your age:  24
Enter your sex (male/female):  male
Enter your BMI:  90
Enter number of children:  0
Are you a smoker? (yes/no):  no
Enter your region (southwest/southeast/northwest/northeast):  northeast

========== Insurance Prediction ==========
Age              : 24
Sex              : male
BMI              : 90.0
Children         : 0
Smoker           : no
Region           : northeast
------------------------------------------
Predicted Charges : $[25198.85029148]
==========================================